### ISSUE TITLE
Post-release fixes #1

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/one.compost.digital#29]
This is the first round of fixes that we will do on the weekend of March 14th

Current issues:
- [x] "inustice" on Zach's piece
- [x] Release date in footpage
- [x] Kaoani on front page

**Comment by maisutton** [comment]
- [x] AC's piece: homogenity > homogeneity (half-way through piece)
- [x] Zach's piece: it’s a cheeky title (space after comma)
- Tal's piece: Funkiness in #23 formatting -- should the parenthetical part be in the footnote?
- [x] Foreword: Add "community networks" in the sentence "Our team of contributors and collaborators work in and for solidarity economics, ..."

**Comment by uditvira** [comment]
- [x] change image rendering to pixelated on anigifs
```
image-rendering: -moz-crisp-edges;
image-rendering: pixelated;
```
